version: '3'

services:
  web_server:
    image: nginx:latest
    ports:
      - "80:80"
  check_web_server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web_server